/**
 * harvest-token.js
 *
 * Reads the Playwright auth state (generated by e2e-tests global setup),
 * extracts the active Clerk session ID, and uses the Clerk Backend SDK to
 * generate a long-lived JWT via the "load-test" JWT template.
 *
 * The resulting token is written to TEST_AUTH_TOKEN in .env so load tests
 * can authenticate without manual browser steps.
 *
 * Prerequisites:
 *   1. Create a JWT template named "load-test" in Clerk Dashboard:
 *      Dashboard → JWT Templates → New template → Blank
 *      Set Token Lifetime to 31536000 (1 year)
 *      Leave claims empty (or copy from your default session token template)
 *
 *   2. Set CLERK_SECRET_KEY in load-tests/.env
 *
 *   3. Have a valid Playwright auth state:
 *      cd ../e2e-tests && pnpm install && pnpm exec playwright install chromium
 *      Copy .env.test.example to .env.test, fill in TEST_USER_EMAIL / TEST_USER_PASSWORD
 *      pnpm test:smoke  (this runs global-setup and generates onboarded-user.json)
 *
 * Usage:
 *   cd load-tests
 *   pnpm harvest-token
 */

import { createClerkClient } from '@clerk/backend';
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENV_PATH = join(__dirname, '../.env');
const AUTH_STATE_PATH = join(__dirname, '../../e2e-tests/fixtures/auth-state/onboarded-user.json');
const JWT_TEMPLATE = process.env.CLERK_JWT_TEMPLATE || 'load-test';

dotenv.config({ path: ENV_PATH });

async function main() {
  const secretKey = process.env.CLERK_SECRET_KEY;
  if (!secretKey) {
    console.error('❌ CLERK_SECRET_KEY is not set in load-tests/.env');
    console.error('   Add: CLERK_SECRET_KEY=sk_live_... (or sk_test_...)');
    process.exit(1);
  }

  // ── 1. Read Playwright auth state ────────────────────────────────────────
  let authState;
  try {
    authState = JSON.parse(readFileSync(AUTH_STATE_PATH, 'utf8'));
  } catch {
    console.error('❌ Could not read Playwright auth state:');
    console.error(`   ${AUTH_STATE_PATH}`);
    console.error('   Generate it by running the e2e tests once:');
    console.error('   cd ../e2e-tests && pnpm test:smoke');
    process.exit(1);
  }

  // ── 2. Extract __session cookie (Clerk short-lived JWT) ──────────────────
  const sessionCookie = authState.cookies?.find((c) => c.name === '__session');
  if (!sessionCookie?.value) {
    console.error('❌ No __session cookie found in Playwright auth state.');
    console.error('   The auth state may be stale. Re-run the e2e tests to refresh it.');
    process.exit(1);
  }

  // ── 3. Decode JWT payload to get session ID (no signature check needed) ──
  let sessionId;
  try {
    const payloadB64 = sessionCookie.value.split('.')[1];
    const payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8'));
    sessionId = payload.sid;
  } catch {
    console.error('❌ Failed to decode __session JWT payload.');
    process.exit(1);
  }

  if (!sessionId) {
    console.error('❌ sid (session ID) claim missing from __session JWT.');
    process.exit(1);
  }

  console.log(`📋 Session ID : ${sessionId}`);
  console.log(`🔑 JWT template: ${JWT_TEMPLATE}`);

  // ── 4. Exchange session ID for a long-lived JWT via Clerk Backend SDK ─────
  const clerk = createClerkClient({ secretKey });
  let jwt;
  try {
    const result = await clerk.sessions.getToken(sessionId, JWT_TEMPLATE);
    jwt = result.jwt;
  } catch (err) {
    console.error(`❌ Clerk sessions.getToken() failed: ${err.message}`);
    console.error('   Possible causes:');
    console.error('   • The Playwright auth state is expired (re-run e2e tests)');
    console.error(`   • The JWT template "${JWT_TEMPLATE}" does not exist in Clerk Dashboard`);
    console.error('   • CLERK_SECRET_KEY belongs to the wrong Clerk instance');
    process.exit(1);
  }

  // ── 5. Write TEST_AUTH_TOKEN to .env ──────────────────────────────────────
  let envContent = readFileSync(ENV_PATH, 'utf8');
  if (/^TEST_AUTH_TOKEN=/m.test(envContent)) {
    envContent = envContent.replace(/^TEST_AUTH_TOKEN=.*/m, `TEST_AUTH_TOKEN=${jwt}`);
  } else {
    envContent += `\nTEST_AUTH_TOKEN=${jwt}\n`;
  }
  writeFileSync(ENV_PATH, envContent);

  console.log('✅ TEST_AUTH_TOKEN written to load-tests/.env');
  console.log('\nReady to run:');
  console.log('  pnpm test:study-room');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
